[game]
hostname = "Ванилла Space Axolotl [RU][LRP][MRP]"
desc = "Сервер с действительно ванильной сборкой на русском языке.\nОтсутствие целей станции, СРП, АВД, душных правил и законов.\nИменно так, как задумывали разработчики."
maxplayers = 150
soft_max_players = 50
map_rotation = true

[rules]
time = 60.0

[hub]
advertise = true
tags = "lang:ru,rp:low,rp:med,region:eu_e"
